import { FieldTypeEnum, FieldDisplayModeEnum, ContactFields, QuotaTypes } from './contact';

export const defaultContactFields: ContactFields = {
    picture: {
        id: 'picture',
        enabled: true,
        name: 'Photo',
        type: FieldTypeEnum.Image,
        position: 6,
        isSystem: true,
        display: {
            contactList: FieldDisplayModeEnum.Writable,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
    firstName: {
        id: 'firstName',
        enabled: true,
        name: 'Prénom',
        type: FieldTypeEnum.Text,
        position: 1,
        isSystem: true,
        display: {
            contactList: FieldDisplayModeEnum.Writable,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Writable,
            formFields: FieldDisplayModeEnum.Writable,
        },
    },
    lastName: {
        id: 'lastName',
        enabled: true,
        name: 'Nom',
        type: FieldTypeEnum.Text,
        position: 2,
        isSystem: true,
        display: {
            contactList: FieldDisplayModeEnum.Writable,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Writable,
            formFields: FieldDisplayModeEnum.Writable,
        },
    },
    email: {
        id: 'email',
        enabled: true,
        name: 'Email',
        type: FieldTypeEnum.Text,
        position: 3,
        isSystem: true,
        display: {
            contactList: FieldDisplayModeEnum.Writable,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Writable,
            formFields: FieldDisplayModeEnum.ReadOnly,
        },
    },
    mobile: {
        id: 'mobile',
        enabled: true,
        name: 'Téléphone mobile',
        type: FieldTypeEnum.Text,
        position: 4,
        isSystem: true,
        display: {
            contactList: FieldDisplayModeEnum.Writable,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
    enterprise: {
        id: 'enterprise',
        enabled: true,
        name: 'Entreprise',
        type: FieldTypeEnum.Text,
        position: 4,
        isSystem: true,
        display: {
            contactList: FieldDisplayModeEnum.Writable,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
    status: {
        id: 'status',
        enabled: true,
        name: 'Statut',
        type: FieldTypeEnum.Group,
        position: 6,
        isSystem: true,
        display: {
            contactList: FieldDisplayModeEnum.Writable,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
        options: {
            groups: [
                {
                    value: -1,
                    position: 0,
                    name: 'Ne vient pas',
                    quotas: { [QuotaTypes.QuotaCheckin]: 0, [QuotaTypes.QuotaSubscription]: 0 },
                },
                {
                    value: 0,
                    position: 1,
                    name: 'Sans réponse',
                    quotas: { [QuotaTypes.QuotaCheckin]: 0, [QuotaTypes.QuotaSubscription]: 0 },
                },
                {
                    value: 1,
                    position: 2,
                    name: 'Peut-être',
                    quotas: { [QuotaTypes.QuotaCheckin]: 0, [QuotaTypes.QuotaSubscription]: 0 },
                },
                {
                    value: 2,
                    position: 3,
                    name: 'Oui',
                    quotas: { [QuotaTypes.QuotaCheckin]: 0, [QuotaTypes.QuotaSubscription]: 0 },
                },
            ],
            multiple: false,
            defaultValue: 0,
        },
    },
    optin: {
        id: 'optin',
        enabled: true,
        name: 'Inscription Emails',
        type: FieldTypeEnum.YesNo,
        options: {
            groups: [{ value: 0, name: 'Non' }, { value: 1, name: 'Oui' }],
        },
        position: 2,
        isSystem: true,
        display: {
            contactList: FieldDisplayModeEnum.Writable,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
    champ0: {
        id: 'champ0',
        enabled: false,
        name: '',
        type: FieldTypeEnum.Text,
        position: 20,
        isSystem: false,
        display: {
            contactList: FieldDisplayModeEnum.Hidden,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
    champ1: {
        id: 'champ1',
        enabled: false,
        name: '',
        type: FieldTypeEnum.Text,
        position: 20,
        isSystem: false,
        display: {
            contactList: FieldDisplayModeEnum.Hidden,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
    champ2: {
        id: 'champ2',
        enabled: false,
        name: '',
        type: FieldTypeEnum.Text,
        position: 20,
        isSystem: false,
        display: {
            contactList: FieldDisplayModeEnum.Writable,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
    champ3: {
        id: 'champ3',
        enabled: false,
        name: '',
        type: FieldTypeEnum.Text,
        position: 20,
        isSystem: false,
        display: {
            contactList: FieldDisplayModeEnum.Hidden,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
    champ4: {
        id: 'champ4',
        enabled: false,
        name: '',
        type: FieldTypeEnum.Text,
        position: 20,
        isSystem: false,
        display: {
            contactList: FieldDisplayModeEnum.Hidden,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
    champ5: {
        id: 'champ5',
        enabled: false,
        name: '',
        type: FieldTypeEnum.Text,
        position: 20,
        isSystem: false,
        display: {
            contactList: FieldDisplayModeEnum.Hidden,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
    champ6: {
        id: 'champ6',
        enabled: false,
        name: '',
        type: FieldTypeEnum.Text,
        position: 20,
        isSystem: false,
        display: {
            contactList: FieldDisplayModeEnum.Hidden,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
    champ7: {
        id: 'champ7',
        enabled: false,
        name: '',
        type: FieldTypeEnum.Text,
        position: 20,
        isSystem: false,
        display: {
            contactList: FieldDisplayModeEnum.Hidden,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
    champ8: {
        id: 'champ8',
        enabled: false,
        name: '',
        type: FieldTypeEnum.Text,
        position: 20,
        isSystem: false,
        display: {
            contactList: FieldDisplayModeEnum.Hidden,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
    champ9: {
        id: 'champ9',
        enabled: false,
        name: '',
        type: FieldTypeEnum.Text,
        position: 20,
        isSystem: false,
        display: {
            contactList: FieldDisplayModeEnum.Hidden,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
    champ10: {
        id: 'champ10',
        enabled: false,
        name: '',
        type: FieldTypeEnum.Text,
        position: 20,
        isSystem: false,
        display: {
            contactList: FieldDisplayModeEnum.Hidden,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
    champ11: {
        id: 'champ11',
        enabled: false,
        name: '',
        type: FieldTypeEnum.Text,
        position: 20,
        isSystem: false,
        display: {
            contactList: FieldDisplayModeEnum.Hidden,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
    champ12: {
        id: 'champ12',
        enabled: false,
        name: '',
        type: FieldTypeEnum.Text,
        position: 20,
        isSystem: false,
        display: {
            contactList: FieldDisplayModeEnum.Hidden,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
    champ13: {
        id: 'champ13',
        enabled: false,
        name: '',
        type: FieldTypeEnum.Text,
        position: 20,
        isSystem: false,
        display: {
            contactList: FieldDisplayModeEnum.Hidden,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
    champ14: {
        id: 'champ14',
        enabled: false,
        name: '',
        type: FieldTypeEnum.Text,
        position: 20,
        isSystem: false,
        display: {
            contactList: FieldDisplayModeEnum.Hidden,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
    champ15: {
        id: 'champ15',
        enabled: false,
        name: '',
        type: FieldTypeEnum.Text,
        position: 20,
        isSystem: false,
        display: {
            contactList: FieldDisplayModeEnum.Hidden,
            checkin: FieldDisplayModeEnum.Hidden,
            checkinNewContact: FieldDisplayModeEnum.Hidden,
            formFields: FieldDisplayModeEnum.Hidden,
        },
    },
};
